---
- name: deploy ONOS to the target machine
  hosts: "{{ target | default('localhost') }}"
  become: true
  connection: local
  environment:
    JAVA_HOME: "/usr/lib/jvm/jre-openjdk"
    PATH: "/usr/lib/jvm/jre-openjdk:{{ ansible_env.PATH }}"
    ONOS_USER: sdn
    ONOS_APPS: drivers,openflow
    PYTHONHTTPSVERIFY: 0

  pre_tasks:
    - debug: msg="##### start ONOS deployment {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"

    - file:
        path: "{{ lookup('env','HOME') }}/ansible.log"
        state: touch
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "u=rw,g=rw,o=rw"

  roles:
    - openjdk
    - onos

  post_tasks:
    - debug: msg="##### ending ONOS deployment {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"

